version: '2'
services:
  geth:
    image: "ethereum/client-go:stable"
    restart: always
    container_name: "geth-rinkeby"
    command: "--rinkeby --rpc --rpcapi=db,eth,net,web3,personal,web3 --rpcaddr '0.0.0.0' --rpcport 8545 --ws --wsaddr '0.0.0.0' --wsport 8546 --syncmode fast --verbosity 2"
    volumes:
      - "$HOME/.ethereum-docker/rinkeby/:/root/.ethereum/"
    ports:
      - 8545:8545
      - 8546:8546